kind: Service
apiVersion: v1
metadata:
  name: $APPNAME
  namespace: $APPNAME
spec:
  type: NodePort
  selector:
    app: $APPNAME
  ports:
  - protocol: TCP
    port: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $APPNAME-deployment
  namespace: $APPNAME
  labels:
    app: $APPNAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APPNAME
  template:
    metadata:
      labels:
        app: $APPNAME
    spec:
      containers:
      - name: $APPNAME
        image: $IMAGETAG
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: $APPNAME
  name: $APPNAME
  namespace: $APPNAME
spec:
  backend:
    serviceName: $APPNAME
    servicePort: 3000